import asyncio
import os
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

MONGODB_URI = os.getenv(
    "MONGODB_URI",
    "mongodb+srv://conceptraedu_db_user:FRk5gYmp4TVn6Xqm@cluster0.5q11fff.mongodb.net/aridhu_db?retryWrites=true&w=majority&appName=Cluster0"
)

categories = [
    {
        "name": "Rasam Powders",
        "slug": "rasam",
        "description": "7-Day authentic South Indian daily Rasam ritual podis.",
        "icon": "🥣",
        "displayOrder": 1,
    },
    {
        "name": "Kozhambu Powders",
        "slug": "kozhambu",
        "description": "Traditional Tanjore gravy spice blends.",
        "icon": "🍲",
        "displayOrder": 2,
    },
]

products = [
    # 7 RASAMS
    {
        "name": "Kalyana Rasam Powder",
        "slug": "kalyana-rasam-powder",
        "subtitle": "Grand Wedding Feast Aroma",
        "tamilName": "கல்யாண ரசம்",
        "price": 100,
        "originalPrice": 120,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-rasam",
        "categorySlug": "rasam",
        "tags": ["rasam", "festive", "traditional", "monday-ritual"],
        "featured": True,
        "status": "active",
        "imageUrl": "assets/images/kalyana-rasam.png",
        "shortDescription": "Festive Tamil wedding feast style rasam powder slow-roasted with Salem coriander and Tellicherry black pepper.",
        "description": "Kalyana Rasam is the soul of Tanjore marriage banquets. Hand-roasted whole spices coarsely pounded to release rich festive essential oils.",
        "usage": "Add 1.5 tsp powder to 500ml tamarind water with fresh tomatoes and coriander.",
        "storage": "Store in an airtight ceramic or stainless steel container away from direct sunlight.",
        "recipe": {
            "title": "Grand Wedding Feast Kalyana Rasam",
            "prepTime": "5 mins",
            "cookTime": "10 mins",
            "servings": "3-4 Servings",
            "ingredients": [
                "1.5 tsp Aridhu Kalyana Rasam Powder",
                "1 lemon-sized ball Tamarind (extracted in 2 cups water)",
                "2 medium ripe Tomatoes (chopped)",
                "1/2 cup cooked Toor Dal (mashed smoothly)",
                "1 tsp Pure Ghee",
                "1/2 tsp Mustard seeds & Cumin seeds",
                "Fresh Curry leaves & chopped Coriander"
            ],
            "instructions": [
                "Extract tamarind juice into a vessel. Add chopped tomatoes, salt, turmeric, and 1.5 tsp Aridhu Kalyana Rasam Powder.",
                "Boil on medium heat for 7-8 minutes until raw tamarind aroma vanishes.",
                "Add the cooked mashed toor dal along with 1.5 cups of water.",
                "Simmer gently on low flame until a golden frothy foam covers the top. Do not boil hard.",
                "Heat ghee in a tempering pan, pop mustard seeds, cumin, and curry leaves, then pour into the rasam.",
                "Garnish with fresh coriander and cover immediately to seal in the Tanjore banquet aroma."
            ],
            "tips": "Always switch off the flame as soon as rasam turns frothy on top to retain essential spice oils."
        },
        "inStock": True,
    },
    {
        "name": "Poricha Rasam Powder",
        "slug": "poricha-rasam-powder",
        "subtitle": "Lentil & Cumin Comfort Blend",
        "tamilName": "பொரிச்ச ரசம்",
        "price": 100,
        "originalPrice": 120,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-rasam",
        "categorySlug": "rasam",
        "tags": ["rasam", "lentil", "comfort", "tuesday-ritual"],
        "featured": False,
        "status": "active",
        "imageUrl": "assets/images/poricha-rasam.png",
        "shortDescription": "Gentle, protein-rich roasted lentil rasam blend for quiet home meals.",
        "description": "Coarsely crushed roasted toor dal and pepper providing soothing digestive warmth.",
        "usage": "Simmer with cooked tuvar dal water and temper with mustard seeds and curry leaves in ghee.",
        "storage": "Keep sealed in a cool, dry pantry.",
        "inStock": True,
    },
    {
        "name": "Elavangapattai Rasam Powder",
        "slug": "elavangapattai-rasam-powder",
        "subtitle": "Cinnamon & Spice Bark Warmth",
        "tamilName": "இலவங்கப்பட்டை ரசம்",
        "price": 100,
        "originalPrice": 120,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-rasam",
        "categorySlug": "rasam",
        "tags": ["rasam", "cinnamon", "aromatic", "wednesday-ritual"],
        "featured": False,
        "status": "active",
        "imageUrl": "assets/images/elavangapattai-rasam.png",
        "shortDescription": "Infused with sweet Ceylon cinnamon bark for a royal Tanjore aroma.",
        "description": "Rare heritage blend pairing slow-roasted cinnamon bark with coriander and Guntur chillies.",
        "usage": "Boil with ripe tomatoes and tamarind extract; finish with chopped coriander.",
        "storage": "Aroma-sealed foil pouch.",
        "inStock": True,
    },
    {
        "name": "Thalippu Milagu Rasam Powder",
        "slug": "thalippu-milagu-rasam-powder",
        "subtitle": "Tempered Black Pepper Remedy",
        "tamilName": "தாளித்த மிளகு ரசம்",
        "price": 100,
        "originalPrice": 120,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-rasam",
        "categorySlug": "rasam",
        "tags": ["rasam", "pepper", "immunity", "thursday-ritual"],
        "featured": True,
        "status": "active",
        "imageUrl": "assets/images/thalippu-milagu-rasam.png",
        "shortDescription": "Peppery restorative blend crafted for throat comfort and immunity.",
        "description": "Tellicherry black pepper hand-crushed with cumin to clear congestion and warm the body.",
        "usage": "Boil Tamarind juice with 1.5 tsp powder, temper liberally with A2 ghee and mustard seeds.",
        "storage": "Store in clean dry glass jar.",
        "inStock": True,
    },
    {
        "name": "Inji Elumichai Rasam Powder",
        "slug": "inji-elumichai-rasam-powder",
        "subtitle": "Ginger & Tangy Citrus Zest",
        "tamilName": "இஞ்சி எலுமிச்சை ரசம்",
        "price": 100,
        "originalPrice": 120,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-rasam",
        "categorySlug": "rasam",
        "tags": ["rasam", "ginger", "lemon", "friday-ritual"],
        "featured": False,
        "status": "active",
        "imageUrl": "assets/images/inji-elumichai-rasam.png",
        "shortDescription": "Invigorating ginger rasam powder designed for fresh lemon juice pairing.",
        "description": "Dry sun-cured ginger root pounded with coriander seeds for a refreshing tangy palate cleanser.",
        "usage": "Boil light dal broth with powder, remove from heat and squeeze fresh lemon juice before serving.",
        "storage": "Keep cool and sealed.",
        "inStock": True,
    },
    {
        "name": "Kandathippili Rasam Powder",
        "slug": "kandathippili-rasam-powder",
        "subtitle": "Long Pepper Medicinal Lineage",
        "tamilName": "கண்டத்திப்பிலி ரசம்",
        "price": 100,
        "originalPrice": 130,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-rasam",
        "categorySlug": "rasam",
        "tags": ["rasam", "ayurvedic", "long-pepper", "saturday-ritual"],
        "featured": True,
        "status": "active",
        "imageUrl": "assets/images/kandathippili-rasam.png",
        "shortDescription": "Precious herbal rasam podi featuring wild Kandathippili (long pepper stem).",
        "description": "Traditional Siddha-inspired rasam recipe known for healing body aches and boosting immunity.",
        "usage": "Simmer with mild tamarind water and ghee; drink warm as soup or serve with Ponni rice.",
        "storage": "Preserve in airtight brass or ceramic container.",
        "inStock": True,
    },
    {
        "name": "Kollu Rasam Powder",
        "slug": "kollu-rasam-powder",
        "subtitle": "Horsegram Detox & Energy Blend",
        "tamilName": "கொள்ளு ரசம்",
        "price": 100,
        "originalPrice": 120,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-rasam",
        "categorySlug": "rasam",
        "tags": ["rasam", "horsegram", "detox", "sunday-ritual"],
        "featured": False,
        "status": "active",
        "imageUrl": "assets/images/kollu-rasam.png",
        "shortDescription": "Nutritious roasted horsegram rasam powder packed with iron and protein.",
        "description": "Iron-kadai roasted horsegram coarsely hand-pounded for a wholesome Sunday family meal.",
        "usage": "Cook with crushed garlic, tomatoes, and tamarind water.",
        "storage": "Store in dry place.",
        "inStock": True,
    },

    # 7 KOZHAMBUS
    {
        "name": "Vatha Kozhambu Powder",
        "slug": "vatha-kozhambu-powder",
        "subtitle": "Sundried Berry Tangy Gravy",
        "tamilName": "வத்த குழம்பு",
        "price": 100,
        "originalPrice": 120,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-kozhambu",
        "categorySlug": "kozhambu",
        "tags": ["kozhambu", "tangy", "vathal", "heritage"],
        "featured": True,
        "status": "active",
        "imageUrl": "assets/images/vatha-kozhambu.png",
        "shortDescription": "Intense tangy sesame-roasted gravy powder perfect for Sundakkai & Manathakkali vathal.",
        "description": "Classic Tanjore style Vatha Kozhambu masala crafted with dark-roasted coriander, red chillies, and fenugreek.",
        "usage": "Sauté vathal in gingelly oil, add tamarind extract and 2 tbsp powder; simmer till oil separates.",
        "storage": "Cool dry pantry.",
        "inStock": True,
    },
    {
        "name": "Pundu Kozhambu Powder",
        "slug": "pundu-kozhambu-powder",
        "subtitle": "Garlic & Black Pepper Masala",
        "tamilName": "பூண்டு குழம்பு",
        "price": 100,
        "originalPrice": 120,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-kozhambu",
        "categorySlug": "kozhambu",
        "tags": ["kozhambu", "garlic", "robust"],
        "featured": False,
        "status": "active",
        "imageUrl": "assets/images/pundu-kozhambu.png",
        "shortDescription": "Robust spice blend specially formulated for whole garlic pearl curries.",
        "description": "Fragrant blend of cumin, red chillies, and mustard designed to pair with slow-cooked garlic cloves.",
        "usage": "Sauté whole garlic cloves in gingelly oil, add tamarind juice and powder.",
        "storage": "Keep airtight.",
        "inStock": True,
    },
    {
        "name": "Kara Kozhambu Powder",
        "slug": "kara-kozhambu-powder",
        "subtitle": "Fiery Chettinad Style Spicy Gravy",
        "tamilName": "கார குழம்பு",
        "price": 100,
        "originalPrice": 120,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-kozhambu",
        "categorySlug": "kozhambu",
        "tags": ["kozhambu", "spicy", "chettinad"],
        "featured": False,
        "status": "active",
        "imageUrl": "assets/images/kara-kozhambu.png",
        "shortDescription": "Bold & spicy red chilli gravy masala for brinjal, drumstick, and colocasia.",
        "description": "Fiery sun-dried Guntur chillies combined with roasted chana dal and black pepper.",
        "usage": "Cook with preferred vegetables in tamarind sauce.",
        "storage": "Sealed foil container.",
        "inStock": True,
    },
    {
        "name": "Milagu Kozhambu Powder",
        "slug": "milagu-kozhambu-powder",
        "subtitle": "Dark Pepper & Cumin Medicinal Curry",
        "tamilName": "மிளகு குழம்பு",
        "price": 100,
        "originalPrice": 130,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-kozhambu",
        "categorySlug": "kozhambu",
        "tags": ["kozhambu", "pepper", "postpartum", "healing"],
        "featured": True,
        "status": "active",
        "imageUrl": "assets/images/milagu-kozhambu.png",
        "shortDescription": "Deep dark medicinal pepper gravy powder cherished for post-natal and winter care.",
        "description": "Heavy iron-kadai roasted black pepper and cumin pounded without added turmeric for rich dark color.",
        "usage": "Simmer tamarind paste with powder in Gingelly oil until thick sauce forms.",
        "storage": "Store in glass jar.",
        "inStock": True,
    },
    {
        "name": "Mor Kozhambu Powder",
        "slug": "mor-kozhambu-powder",
        "subtitle": "Spiced Buttermilk & Coconut Gravy",
        "tamilName": "மோர் குழம்பு",
        "price": 100,
        "originalPrice": 120,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-kozhambu",
        "categorySlug": "kozhambu",
        "tags": ["kozhambu", "buttermilk", "cooling"],
        "featured": False,
        "status": "active",
        "imageUrl": "assets/images/mor-kozhambu.png",
        "shortDescription": "Cooling, aromatic ground cumin and coriander spice mix for buttermilk curries.",
        "description": "Subtle green chilli and cumin profile engineered for ash gourd and yellow pumpkin mor kozhambu.",
        "usage": "Mix powder into whisked sour curd/buttermilk, pour over cooked gourd, and temper gently.",
        "storage": "Keep dry.",
        "inStock": True,
    },
    {
        "name": "Ennai Kathirikai Kozhambu Powder",
        "slug": "ennai-kathirikai-kozhambu-powder",
        "subtitle": "Stuffed Brinjal Sesame Gravy",
        "tamilName": "எண்ணெய் கத்திரிக்காய்",
        "price": 100,
        "originalPrice": 130,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-kozhambu",
        "categorySlug": "kozhambu",
        "tags": ["kozhambu", "brinjal", "festive"],
        "featured": True,
        "status": "active",
        "imageUrl": "assets/images/ennai-kathirikai.png",
        "shortDescription": "Rich roasted sesame & coriander stuffing powder for small tender brinjals.",
        "description": "Aromatic roasted sesame and coriander stuffing mix that caramelizes inside fried brinjals.",
        "usage": "Stuff slit brinjals with powder, shallow fry in oil, and simmer in tamarind gravy.",
        "storage": "Cool dry storage.",
        "inStock": True,
    },
    {
        "name": "Thakkali Kozhambu Powder",
        "slug": "thakkali-kozhambu-powder",
        "subtitle": "Tangy Tomato Tiffin Gravy",
        "tamilName": "தக்காளி குழம்பு",
        "price": 100,
        "originalPrice": 120,
        "weight": 100,
        "unit": "g",
        "categoryId": "cat-kozhambu",
        "categorySlug": "kozhambu",
        "tags": ["kozhambu", "tomato", "tiffin"],
        "featured": False,
        "status": "active",
        "imageUrl": "assets/images/thakkali-kozhambu.png",
        "shortDescription": "Versatile tomato curry powder perfect for Idli, Dosa, and Ponni rice.",
        "description": "Mildly spiced tomato gravy masala blending coriander, fennel, and coconut notes.",
        "usage": "Saute chopped tomatoes and onions, add powder and water; simmer for 10 minutes.",
        "storage": "Aroma tight pouch.",
        "inStock": True,
    },
]

combos = [
    {
        "name": "7 Rasam Collection Box",
        "slug": "7-rasam-collection",
        "subtitle": "Weekly Daily Rasam Heritage Ritual",
        "tamilName": "ஏழு நாள் ரசம் சடங்கு பெட்டி",
        "price": 350,
        "originalPrice": 700,
        "totalWeight": 700,
        "itemCount": 7,
        "featured": True,
        "imageUrl": "assets/images/7-rasam-box.png",
        "description": "Complete 7-day authentic Tanjore rasam ritual collection containing one 100g pack of each unique Rasam blend.",
        "items": [
            {"productId": "r1", "productSlug": "kalyana-rasam-powder", "name": "Kalyana Rasam Powder", "tamilName": "கல்யாண ரசம்", "weight": 100},
            {"productId": "r2", "productSlug": "poricha-rasam-powder", "name": "Poricha Rasam Powder", "tamilName": "பொரிச்ச ரசம்", "weight": 100},
            {"productId": "r3", "productSlug": "elavangapattai-rasam-powder", "name": "Elavangapattai Rasam Powder", "tamilName": "இலவங்கப்பட்டை ரசம்", "weight": 100},
            {"productId": "r4", "productSlug": "thalippu-milagu-rasam-powder", "name": "Thalippu Milagu Rasam Powder", "tamilName": "தாளித்த மிளகு ரசம்", "weight": 100},
            {"productId": "r5", "productSlug": "inji-elumichai-rasam-powder", "name": "Inji Elumichai Rasam Powder", "tamilName": "இஞ்சி எலுமிச்சை ரசம்", "weight": 100},
            {"productId": "r6", "productSlug": "kandathippili-rasam-powder", "name": "Kandathippili Rasam Powder", "tamilName": "கண்டத்திப்பிலி ரசம்", "weight": 100},
            {"productId": "r7", "productSlug": "kollu-rasam-powder", "name": "Kollu Rasam Powder", "tamilName": "கொள்ளு ரசம்", "weight": 100},
        ],
    },
    {
        "name": "7 Kozhambu Collection Box",
        "slug": "7-kozhambu-collection",
        "subtitle": "Signature Gravy Heritage Ritual",
        "tamilName": "ஏழு நாள் குழம்பு சடங்கு பெட்டி",
        "price": 350,
        "originalPrice": 700,
        "totalWeight": 700,
        "itemCount": 7,
        "featured": True,
        "imageUrl": "assets/images/7-kozhambu-box.png",
        "description": "Complete 7-day authentic Tanjore gravy collection containing one 100g pack of each signature Kozhambu masala.",
        "items": [
            {"productId": "k1", "productSlug": "vatha-kozhambu-powder", "name": "Vatha Kozhambu Powder", "tamilName": "வத்த குழம்பு", "weight": 100},
            {"productId": "k2", "productSlug": "pundu-kozhambu-powder", "name": "Pundu Kozhambu Powder", "tamilName": "பூண்டு குழம்பு", "weight": 100},
            {"productId": "k3", "productSlug": "kara-kozhambu-powder", "name": "Kara Kozhambu Powder", "tamilName": "கார குழம்பு", "weight": 100},
            {"productId": "k4", "productSlug": "milagu-kozhambu-powder", "name": "Milagu Kozhambu Powder", "tamilName": "மிளகு குழம்பு", "weight": 100},
            {"productId": "k5", "productSlug": "mor-kozhambu-powder", "name": "Mor Kozhambu Powder", "tamilName": "மோர் குழம்பு", "weight": 100},
            {"productId": "k6", "productSlug": "ennai-kathirikai-kozhambu-powder", "name": "Ennai Kathirikai Kozhambu Powder", "tamilName": "எண்ணெய் கத்திரிக்காய்", "weight": 100},
            {"productId": "k7", "productSlug": "thakkali-kozhambu-powder", "name": "Thakkali Kozhambu Powder", "tamilName": "தக்காளி குழம்பு", "weight": 100},
        ],
    },
]

async def seed():
    client = AsyncIOMotorClient(MONGODB_URI)
    db = client.get_default_database("aridhu_db")
    print("Connected to MongoDB Atlas...")

    # Clear existing collections
    await db.categories.delete_many({})
    await db.products.delete_many({})
    await db.combos.delete_many({})

    print("Cleared existing database collections...")

    await db.categories.insert_many(categories)
    print("Categories seeded (2)")

    await db.products.insert_many(products)
    print("Products seeded (14)")

    await db.combos.insert_many(combos)
    print("Combo Collections seeded (2)")

    print("Python MongoDB Atlas Seeding Complete!")

if __name__ == "__main__":
    asyncio.run(seed())
